<a href="https://colab.research.google.com/github/msap-uai/PythonDeepLearning/blob/main/Capitulo_3_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Librerias
Libreria de relevancia para usar

1. **NumPy** es la librería que permite un cálculo numérico fácil y eficiente, y la librería sobre la que muchas otras librerías están construidas. 
2. **Pandas** es una librería para estructuras de datos y análisis exploratorios 
que está construida sobre NumPy. 
3. **Matplotlib** es una librería de visualización que usaremos a lo largo de 
este libro para presentar diferentes tipos de gráficas. 
4. Scikit-Learn es la principal librería de Machine Learning de uso general 
en Python. Tiene muchos algoritmos y módulos muy populares para pre- 
procesamiento, validación, etc.

Tensor 
Keras usa un array multidimensional de NumPy como estructura básica de datos, y 
llama a esta estructura de datos «tensor». De manera resumida podríamos decir 
que un tensor tiene tres atributos principales: número de ejes, forma y tipo de 
datos. Veamos cada uno de ellos: 
 
* **Número de ejes (rank)** : a un tensor que contiene un solo número lo llama- 
remos scalar (o tensor 0-dimensional, o tensor 0D). Un array de números lo lla- 
mamos vector, o tensor 1D. Un array de vectores será una matriz (matrix) , o 
tensor 2D. Si empaquetamos esta matriz en un nuevo array , obtenemos un ten- 
sor 3D, que podemos interpretar visualmente como un cubo de números. 
Empaquetando un tensor 3D en un array , podemos crear un tensor 4D, y así 
sucesivamente. En la librería NumPy de Python esto se llama ndim del tensor. 
•Forma: se trata de una tupla de enteros que describen cuántas dimensiones 
tiene el tensor en cada eje. En la librería NumPy este atributo se llama shape . 
Un vector tiene un shape con un único elemento, por ejemplo «(5)», mientras 
que un escalar tiene un shape vacío «( )». 

* **Tipo de datos**: este atributo indica el tipo de datos que contiene el tensor, que 
pueden ser por ejemplo uint8 , float32 , float64 , etc. En raras ocasiones tene- 
mos, en nuestro contexto, tensores de tipo char (nunca string ). En la librería 
NumPy este atributo se llama dtype .

In [5]:
import numpy as np # importa libreria
  
x = np.array(8) # crea un array 1D con el valor 8
# x = np.array([2.3 , 4.2 , 3.3, 1.8]) # array 2d?
# x = np.array([[1,2,3], [4,5,6], [7,8,9]]) # 3D
# x = np.array([[[1,2],[3,4]],[[5,6],[7,8]]]) # 4D

print ("x: ", x) 
print ("x ndim: ", x.ndim) # dimenciones
print ("x shape:", x.shape) # forma
print ("x size: ", x.size) # cantidad de elementos
print ("x dtype: ", x.dtype) # tipos de elementos

x:  8
x ndim:  0
x shape: ()
x size:  1
x dtype:  int64


In [ ]:
print ("np.zeros((3,3)):\n", np.zeros((3,3))) # crea tendos de 3x3 de zeros
print ("np.ones((3,3)):\n", np.ones((3,3))) # crea tensor de 3x3 de unos
print ("np.eye((3)): (identity matrix)\n", np.eye((3))) # crea una matriz identidad
print ("np.random.random((3,3)):\n", np.random.random((3,3))) # crea matriz random

Una de las operaciones NumPy más comunes que usaremos es la multipli- 
cación de matrices. Tomamos las filas de nuestra primera matriz (supongamos 2) 
y las columnas de nuestra segunda matriz (supongamos 2) para determinar el pro- 
ducto escalar, lo que nos da una salida de 2 x 2. El único requisito es que las 
dimensiones internas coincidan.

In [6]:
a = np.array([[1,2,3], [4,5,6]], dtype=np.int32) 
b = np.array([[7,8], [9,10], [11, 12]], dtype=np.int32) 
c = a.dot(b) 
print (f"{a.shape} · {b.shape} = {c.shape}") # funcion
print (c)

(2, 3) · (3, 2) = (2, 2)
[[ 58  64]
 [139 154]]


Una transformación que usaremos a menudo será cambiar la forma de los ten- 
sores:

In [8]:
x = np.array([[1,2,3,4,5,6]]) 
print (x) 
print ("x.shape: ", x.shape) 
print()
y = np.reshape(x, (2, 3)) # cambia la forma de la matriz
print ("y: \n", y) 
print ("y.shape: ", y.shape) 
print()
z = np.reshape(x, (2, -1)) # cambia la forma de la matriz
print ("z: \n", z) 
print ("z.shape: ", z.shape)

[[1 2 3 4 5 6]]
x.shape:  (1, 6)
y: 
 [[1 2 3]
 [4 5 6]]
y.shape:  (2, 3)

z: 
 [[1 2 3]
 [4 5 6]]
z.shape:  (2, 3)


cómo añadir dimensiones 
a un tensor. 

In [10]:
x = np.array([[1,2,3],[4,5,6]]) 
print ("x:\n", x)
print ("x.shape: ", x.shape) 

print()

y = np.expand_dims(x, 1) 
print ("y: \n", y) 
print ("y.shape: ", y.shape)

x:
 [[1 2 3]
 [4 5 6]]
x.shape:  (2, 3)

y: 
 [[[1 2 3]]

 [[4 5 6]]]
y.shape:  (2, 1, 3)


cómo borrar dimensiones 
a un tensor. 

In [11]:
x = np.array([[[1,2,3]],[[4,5,6]]]) 
print ("x:\n", x) 
print ("x.shape: ", x.shape) 

y = np.squeeze(x, 1) # elimina la segunda dimencion 
print ("y: \n", y) 
print ("y.shape: ", y.shape)

x:
 [[[1 2 3]]

 [[4 5 6]]]
x.shape:  (2, 1, 3)
y: 
 [[1 2 3]
 [4 5 6]]
y.shape:  (2, 3)


In [12]:
x = np.array([1,2,3,4]) 
print (x) 
  
print (np.argmax(x)) # posicion del valor maximo
print (np.max(x)) # posicion valor maximo

[1 2 3 4]
3
4


In [14]:
x = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

print (np.argmax(x, axis=0)) # en la primera posicion
print (np.max(x, axis=0)) 

print (np.argmax(x, axis=1)) # en la segunda posicion
print (np.max(x, axis=1))

[2 2 2 2]
[ 9 10 11 12]
[3 3 3]
[ 4  8 12]
